export default {
  validInput1: {
    firstname: 'Bruce',
    lastname: 'Banner',
    othernames: 'john',
    email: 'emeisksmusa@yahoo.com',
    password: 'bruce banner',
    phonenumber: '08093056052',
    username: 'jacobUzomwnss',
    isAdmin: 'false',
    registered: 'Date.now()',
    updated: 'Date.now()',
  },
  validInput2: {
    firstname: 'Mike',
    lastname: 'Owen',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phonenumber: '07068566559',
    username: 'chukschukso',
  },

  existingEmail: {
    firstname: 'Barry',
    lastname: 'Allen',
    othernames: 'johnr',
    email: 'mhuk@yahoo.com',
    password: 'theFlash',
    phonenumber: '07068566555',
    username: 'chukschuks',
  },
  // incompleteData: {
  //   firstName: 'Anna',
  //   lastName: 'Jones',
  //   email: 'annie@yahoo.com',
  // },
  // emptyData: {
  //   firstname: '',
  //   lastname: '',
  //   email: '',
  //   othernames: '',
  //   phonenumber: '',
  //   password: '',
  //   username: '',
  // },
  // improperData: {
  //   firstName: '23BruceBanner',
  //   lastName: '1Jones',
  //   email: 'banner@yahoo.com',
  //   password: 'bruce banner',
  // },
  userOneLogin: {
    email: 'banner@yahoo.com', password: 'bruce banner', phonenumber: '07068566559', username: 'chukschuks',
  },
  userTwoLogin: {
    email: 'mikel@yahoo.com',
    password: 'chuks mike',
    // phonenumber: '07068566000',
    // username: 'chuksmike',
  },
  adminLogin: { email: 'amaechichuks2000@yahoo.com.com', password: 'fabulous26' },
  emptyLoginData: { email: '', password: '' },
  noEmail: { email: '', password: 'bruce banner' },
  noPassword: { email: 'mk@yahoo.com', password: '' },
  invalidEmail: { email: 'wrongEmail', password: 'bruce banner' },
  invalidPassword: { email: 'Bruce Banner', password: 'wrongPassword' },
  invalidEmailPassword: { email: 'wrongEmail', password: 'wrongPassword' },
};
