const userDb = [
  {
    id: 1,
    firstname: 'Chineye',
    lastname: 'Frank',
    othernames: '',
    email: 'chineyefrank@gmail.com',
    phoneNumber: '07038890874',
    username: 'ChineyFrank',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 2,
    firstname: 'Christina',
    lastname: 'Bishop',
    othernames: '',
    email: 'christinasass@gmail.com',
    phoneNumber: '07038890871',
    username: 'ChristinaBishop',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 3,
    firstname: 'Hope',
    lastname: 'Abraham',
    othernames: 'E',
    email: 'iyinaboyeji@gmail.com',
    phoneNumber: '07038890872',
    username: 'EAboyeji',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 4,
    firstname: 'Jeremy',
    lastname: 'Johnson',
    othernames: '',
    email: 'jeremyjohnson@gmail.com',
    phoneNumber: '07038890873',
    username: 'Jeremy Johnson',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 5,
    firstname: 'Nadayar',
    lastname: 'Engesi',
    othernames: '',
    email: 'nadayarengesi@gmail.com',
    phoneNumber: '07038890875',
    username: 'NadayarEngesi',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 6,
    firstname: 'Brice',
    lastname: 'Nkengsa',
    othernames: '',
    email: 'bricenkengsa@gmail.com',
    phoneNumber: '07038890876',
    username: 'BriceNkengsa',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 7,
    firstname: 'Omowale',
    lastname: 'David',
    othernames: 'Ashiru',
    email: 'omowaledavid@gmail.com',
    phoneNumber: '07038890877',
    username: 'OmowaleDavid',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 8,
    firstname: 'Evan',
    lastname: 'Green',
    othernames: 'Lowe',
    email: 'evangreen@gmail.com',
    phoneNumber: '07038890874',
    username: 'EvanGreen',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 9,
    firstname: 'Chris',
    lastname: 'James',
    othernames: '',
    email: 'chrisjames@gmail.com',
    phoneNumber: '07038890879',
    username: 'ChrisJames',
    registered: new Date(),
    isAdmin: true,
  },
];

export default userDb;
